#### To install the required packages, run:
<ul>pip install -r requirements.txt</ul>

#### If you want to install a package individually, run:
<ul>pip install package_name</ul>

In [ ]:
import numpy as np

print(np.array([1, 2, 3, 4]))

ModuleNotFoundError: No module named 'numpy'

./venv/Scripts/pip install -r requirements.txt

This is preferable to:

pip install -r requirements.txt

because pip may point to your Miniconda base environment. Since your notebook is using venv so u have to install numpy in venv.

In [8]:
import numpy as np

print(np.__version__)

2.5.3


In [12]:
import numpy as np

print(np.array([1, 2, 3, 4])) # Create a NumPy array from a Python list
print(np.zeros(5)) # Create an array of zeros
print(np.ones(5)) # Create an array of ones
print(np.arange(10)) # Create an array with a range of values
print(np.linspace(0, 1, 5)) # Create an array with linearly spaced values
print(np.random.rand(5)) # Create an array of random values between 0 and 1
print(np.random.randint(0, 10, 5)) # Create an array of random integers
print(np.random.randn(0, 5)) # Create an array of random values from the standard normal distribution
print(np.eye(5)) # Create an identity matrix
print(np.diag([1, 2, 3, 4, 5])) # Create a diagonal matrix
print(np.triu(np.ones((5, 5)))) # Create an upper triangular matrix
print(np.tril(np.ones((5, 5)))) # Create a lower triangular matrix
print(np.full((5, 5), 7)) # Create an array filled with a specific value
print(np.identity(5)) # Create an identity matrix
print(np.random.seed(42)) # Set the random seed for reproducibility

[1 2 3 4]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[2 6 7 4 3]
[]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
None
